#!/bin/sh
set -e

./demog_urban_areas all
./demog_urban_areas nation_by_count
./demog_urban_areas un1

cat output/un_nations_with_uas | while read N
do
  ./demog_urban_areas "$N"
done

(cd output/by_nation; grep -l , *) | while read N
do
  ./demog_urban_areas R:"$N"
done
